name: flutter_offline_map
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  proj4dart: ^2.1.0
  positioned_tap_detector_2: ^1.0.4
  provider: ^6.0.4
  flutter_map_tile_caching: ^6.2.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

